=== ATL-NZ/apteryx/apteryx.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://github.com/alliedtelesis/apteryx"
	xmlns="https://github.com/alliedtelesis/apteryx"
	elementFormDefault="qualified">
	<xs:element name="VALUE">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
			<xs:attribute name="help" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="NODE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NODE" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="VALUE" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="default" type="xs:string" use="optional" />
			<xs:attribute name="pattern" type="xs:string" use="optional" />
			<xs:attribute name="help" type="xs:string" use="optional" />
			<xs:attribute name="mode" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="(h|x|r|w|rw)"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="MODULE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NODE" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ATL-NZ/apteryx/apteryx.xml
<?xml version="1.0" encoding="UTF-8"?>
<MODULE xmlns="https://github.com/ATL-NZ/apteryx"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/ATL-NZ/apteryx
	https://github.com/ATL-NZ/apteryx/releases/download/v1.17/apteryx.xsd">
	<!--=======================================================-->
	<NODE name="apteryx">
		<NODE name="debug" default="0" help="Apteryx debug" value="^(0|1)$">
			<VALUE name="disable" value="0" help="Debugging is disabled" />
			<VALUE name="enable" value="1" help="Debugging is enabled" />
		</NODE>
		<NODE name="sockets" help="List of sockets (urls) that apteryxd will accept connections on.">
			<NODE name="*" help="Unique identifier based on HASH(url). Value is the url to listen on." />
		</NODE>
		<NODE name="watchers" help="List of watched paths and registered callbacks for those watches.">
			<NODE name="*" help="Unique identifier based on PID-CALLBACK-HASH(path). Value is the path." value="^(/)?([^/\0]+(/)?)+$" />
		</NODE>
		<NODE name="providers" help="List of provided paths and registered callbacks for providing gets to that path.">
			<NODE name="*" help="Unique identifier based on PID-CALLBACK-HASH(path). Value is the path." value="^(/)?([^/\0]+(/)?)+$" />
		</NODE>
		<NODE name="validators" help="List of validated paths and registered callbacks for validating sets to that path.">
			<NODE name="*" help="Unique identifier based on PID-CALLBACK-HASH(path). Value is the path." value="^(/)?([^/\0]+(/)?)+$" />
		</NODE>
		<NODE name="proxies" help="List of proxied paths and remote url to proxy gets and sets to.">
			<NODE name="*" help="Unique identifier based on PID-HASH(path)-HASH(url). Value is the full url for the path." value="^(/)?([^/\0]+(/)?)+$" />
		</NODE>
		<NODE name="cache" help="Formatted dump of the Apteryx cache"/>
		<NODE name="counters" help="Formatted list of counters and values for Apteryx usage" />
	</NODE>
</MODULE>
